language: python
dist: focal

python:
  - "3.9"

before_install:
  - sudo add-apt-repository -y ppa:deadsnakes/ppa
  - sudo apt-get -q update
  - sudo apt-get -y install python3.7

install:
  - make develop

jobs:
  include:
    - stage: test
      script: make test
