language: python
dist: focal

python:
  - "3.9"

before_install:
  - sudo add-apt-repository -y ppa:deadsnakes/ppa
  - sudo apt-get -q update
  - sudo apt-get -y install python3.7

install:
  - make develop

jobs:
  include:
    - stage: Unit Tests
      script: make test && bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage.xml
    - stage: Build Wheel
      script: make build

deploy:
  provider: pypi
  username: "__token__"
  password: $PYPI_TOKEN
  skip_existing: true
  on:
    branch: main
